[package]
name = "reverse_proxy_server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
http = "1.2.0"
pingora = { version = "0.4.0", features = ["proxy"] }
pingora-proxy = "0.4.0"
